source "https://github.com/CocoaPods/Specs.git"

platform :ios, "12.0"
inhibit_all_warnings!
use_frameworks! :linkage => :dynamic
install! "cocoapods", :warn_for_unused_master_specs_repo => false

target "WeChatQRCodeScanner" do
  pod "WeChatQRCodeScanner_Swift", :path => "../"
  target "WeChatQRCodeScannerTests" do
    inherit! :search_paths
  end
end
